TEAMS = {
    'Air Force' : 'Air_Force_Falcons',
    'Akron' : 'Akron_Zips',
    'Alabama' : 'Alabama_Crimson_Tide',
    'Alabama A&M' : 'Alabama_A%26M_Bulldogs',
    'Alabama St.' : 'Alabama_State_University',
    'Albany' : 'Albany_Great_Danes',
    'Alcorn St.' : 'Alcorn_State_Braves',
    'Appalachian St.' : 'Appalachian_State_Mountaineers',
    'AR Pine Bluff' : 'Arkansas-Pine_Bluff_Golden_Lions',
    'Arizona' : 'Arizona_Wildcats',
    'Arizona St.' : 'Arizona_State_Sun_Devils',
    'Arkansas' : 'Arkansas_Razorbacks',
    'Arkansas St.' : 'Arkansas_State_Red_Wolves',
    'Army' : 'Army_Black_Knights',
    'Auburn' : 'Auburn_Tigers',
    'Austin Peay' : 'Austin_Peay_State_University',
    'Ball St.' : 'Ball_State_Cardinals',
    'Baylor' : 'Baylor_Bears',
    'Bethune-Cookman' : 'Bethune-Cookman_Wildcats',
    'Boise St.' : 'Boise_State_Broncos',
    'Boston Coll.' : 'Boston_College_Eagles',
    'Bowling Green' : 'Bowling_Green_Falcons',
    'Brown' : 'Brown_Bears',
    'Bryant' : 'Bryant_Bulldogs',
    'Bucknell' : 'Bucknell_Bison',
    'Buffalo' : 'Buffalo_Bulls',
    'Butler' : 'Butler_Bulldogs',
    'BYU' : 'BYU_Cougars',
    'Cal Poly' : 'Cal_Poly_Mustangs',
    'California' : 'California_Golden_Bears',
    'Campbell' : 'Campbell_Fighting_Camels',
    'Cent. Michigan' : 'Central_Michigan_Chippewas',
    'Central Arkansas' : 'Central_Arkansas_Bears',
    'Central Conn. St.' : 'Central_Connecticut_State_University',
    'Charleston Sou.' : 'Charleston_Southern_Buccaneers',
    'Charlotte': 'Charlotte_49ers',
    'Chattanooga' : 'University_of_Tennessee_at_Chattanooga',
    'Cincinnati' : 'Cincinnati_Bearcats',
    'Citadel' : 'The_Citadel_Bulldogs',
    'Clemson' : 'Clemson_Tigers',
    'Coastal Carolina' : 'Coastal_Carolina_Chanticleers',
    'Colgate' : 'Colgate_Raiders',
    'Colorado' : 'Colorado_Buffaloes',
    'Colorado St.' : 'Colorado_State_Rams',
    'Columbia' : 'Columbia_Lions',
    'Connecticut' : 'Connecticut_Huskies',
    'Cornell' : 'Cornell_Big_Red',
    'Dartmouth' : 'Dartmouth_Big_Green',
    'Davidson' : 'Davidson_College',
    'Dayton' : 'Dayton_Flyers',
    'Delaware' : 'Delaware_Fightin%27_Blue_Hens',
    'Delaware St.' : 'Delaware_State_Hornets',
    'Drake' : 'Drake_Bulldogs',
    'Duke' : 'Duke_Blue_Devils',
    'Duquesne' : 'Duquesne_Dukes',
    'East Carolina' : 'East_Carolina_Pirates',
    'East. Michigan' : 'Eastern_Michigan_Eagles',
    'Eastern Illinois' : 'Eastern_Illinois_Panthers',
    'Eastern Kentucky' : 'Eastern_Kentucky_Colonels',
    'Eastern Wash.' : 'Eastern_Washington_Eagles',
    'Elon' : 'Elon_University',
    'Florida' : 'Florida_Gators',
    'Florida A&M' : 'Florida_A%26M_Rattlers',
    'Florida Atlantic' : 'Florida_Atlantic_Owls',
    'Florida Intl.' : 'Florida_International_Golden_Panthers',
    'Florida St.' : 'Florida_State_Seminoles',
    'Fordham' : 'Fordham_Rams',
    'Fresno St.' : 'Fresno_State_Bulldogs',
    'Furman' : 'Furman_University',
    'Gardner-Webb' : 'Gardner-Webb_Runnin%27_Bulldogs',
    'Georgetown' : 'Georgetown_Hoyas',
    'Georgia' : 'Georgia_Bulldogs',
    'Georgia Southern' : 'Georgia_Southern_Eagles',
    'Georgia St.' : 'Georgia_State_Panthers',
    'Georgia Tech' : 'Georgia_Tech_Yellow_Jackets',
    'Grambling St.' : 'Grambling_State_Tigers',
    'Hampton' : 'Hampton_University',
    'Harvard' : 'Harvard_Crimson',
    'Hawaii' : 'Hawaii_Warriors',
    'Holy Cross' : 'Holy_Cross_Crusaders',
    'Houston' : 'Houston_Cougars',
    'Howard' : 'Howard_Bison',
    'Idaho' : 'Idaho_Vandals',
    'Idaho St.' : 'Idaho_State_Bengals',
    'Illinois' : 'Illinois_Fighting_Illini',
    'Illinois St.' : 'Illinois_State_Redbirds',
    'Indiana' : 'Indiana_Hoosiers',
    'Indiana St.' : 'Indiana_State_Sycamores',
    'Iowa' : 'Iowa_Hawkeyes',
    'Iowa St.' : 'Iowa_State_Cyclones',
    'Jackson St.' : 'Jackson_State_Tigers',
    'Jacksonville' : 'Jacksonville_Dolphins',
    'Jacksonville St.' : 'Jacksonville_State_University',
    'James Madison' : 'James_Madison_Dukes',
    'Kansas' : 'Kansas_Jayhawks',
    'Kansas St.' : 'Kansas_State_Wildcats',
    'Kent St.' : 'Kent_State_Golden_Flashes',
    'Kentucky' : 'Kentucky_Wildcats',
    'LA Lafayette' : 'Louisiana-Lafayette_Ragin%27_Cajuns',
    'LA Monroe' : 'Louisiana-Monroe_Warhawks',
    'Lafayette' : 'Lafayette_Leopards',
    'Lamar' : 'Lamar_Cardinals',
    'Lehigh' : 'Lehigh_Mountain_Hawks',
    'Liberty' : 'Liberty_Flames',
    'Louisiana Tech' : 'Louisiana_Tech_Bulldogs',
    'Louisville' : 'Louisville_Cardinals',
    'LSU' : 'LSU_Tigers',
    'Maine' : 'Maine_Black_Bears',
    'Marist' : 'Marist_Red_Foxes',
    'Marshall' : 'Marshall_Thundering_Herd',
    'Maryland' : 'Maryland_Terrapins',
    'Massachusetts' : 'UMass_Minutemen',
    'McNeese St.' : 'McNeese_State_University',
    'Memphis' : 'Memphis_Tigers',
    'Miami (FL)' : 'Miami_Hurricanes',
    'Miami (OH)' : 'Miami_RedHawks',
    'Michigan' : 'Michigan_Wolverines',
    'Michigan St.' : 'Michigan_State_Spartans',
    'Middle Tenn. St.' : 'Middle_Tennessee_Blue_Raiders',
    'Minnesota' : 'Minnesota_Golden_Gophers',
    'Miss. Valley St.' : 'Mississippi_Valley_State_Delta_Devils',
    'Mississippi' : 'Ole_Miss_Rebels',
    'Mississippi St.' : 'Mississippi_State_Bulldogs',
    'Missouri' : 'Missouri_Tigers',
    'Missouri St.' : 'Missouri_State_Bears',
    'Monmouth' : 'Monmouth_University',
    'Montana' : 'Montana_Grizzlies',
    'Montana St.' : 'Montana_State_Bobcats',
    'Morehead St.' : 'Morehead_State_University',
    'Morgan St.' : 'Morgan_State_Bears',
    'Murray St.' : 'Murray_State_Racers',
    'N.C. A&T' : 'North_Carolina_A%26T_Aggies',
    'N.C. Central' : 'North_Carolina_Central_Eagles',
    'N.C. State' : 'North_Carolina_State_Wolfpack',
    'Navy' : 'Navy_Midshipmen',
    'Nebraska' : 'Nebraska_Cornhuskers',
    'Nevada' : 'Nevada_Wolf_Pack',
    'New Hampshire' : 'New_Hampshire_Wildcats',
    'New Mexico' : 'New_Mexico_Lobos',
    'New Mexico St.' : 'New_Mexico_State_Aggies',
    'Nicholls' : 'Nicholls_State_University',
    'Norfolk St.' : 'Norfolk_State_Spartans',
    'North Carolina' : 'North_Carolina_Tar_Heels',
    'North Dakota' : 'University_of_North_Dakota',
    'North Dakota St.' : 'North_Dakota_State_Bison',
    'North Texas' : 'North_Texas_Mean_Green',
    'Northern Arizona' : 'Northern_Arizona_University',
    'Northern Colorado' : 'University_of_Northern_Colorado',
    'Northern Illinois' : 'Northern_Illinois_Huskies',
    'Northern Iowa' : 'Northern_Iowa_Panthers',
    'Northwestern' : 'Northwestern_Wildcats',
    'Northwestern St.' : 'Northwestern_State_Demons',
    'Notre Dame' : 'Notre_Dame_Fighting_Irish',
    'Ohio' : 'Ohio_Bobcats',
    'Ohio St.' : 'Ohio_State_Buckeyes',
    'Oklahoma' : 'Oklahoma_Sooners',
    'Oklahoma St.' : 'Oklahoma_State_Cowboys',
    'Old Dominion' : 'Old_Dominion_Monarchs',
    'Oregon' : 'Oregon_Ducks',
    'Oregon St.' : 'Oregon_State_Beavers',
    'Penn St.' : 'Penn_State_Nittany_Lions',
    'Pennsylvania' : 'Pennsylvania_Quakers',
    'Pittsburgh' : 'Pittsburgh_Panthers',
    'Portland St.' : 'Portland_State_Vikings',
    'Prairie View A&M' : 'Prairie_View_A%26M_Panthers',
    'Presbyterian' : 'Presbyterian_College',
    'Princeton' : 'Princeton_Tigers',
    'Purdue' : 'Purdue_Boilermakers',
    'Rhode Island' : 'Rhode_Island_Rams',
    'Rice' : 'Rice_Owls',
    'Richmond' : 'Richmond_Spiders',
    'Robert Morris' : 'Robert_Morris_Colonials',
    'Rutgers' : 'Rutgers_Scarlet_Knights',
    'S. Carolina St.' : 'South_Carolina_State_Bulldogs',
    'Sacramento St.' : 'California_State_University,_Sacramento',
    'Sacred Heart' : 'Sacred_Heart_University',
    'Sam Houston St.' : 'Sam_Houston_State_Bearkats',
    'Samford' : 'Samford_Bulldogs',
    'San Diego' : 'University_of_San_Diego',
    'San Diego St.' : 'San_Diego_State_Aztecs',
    'San Jose St.' : 'San_Jose_State_Spartans',
    'Savannah St.' : 'Savannah_State_Tigers',
    'SE Louisiana' : 'Southeastern_Louisiana_University',
    'SE Missouri St.' : 'Southeast_Missouri_State_Redhawks',
    'SMU' : 'SMU_Mustangs',
    'South Alabama' : 'South_Alabama_Jaguars',
    'South Carolina' : 'South_Carolina_Gamecocks',
    'South Carolina State': 'South_Carolina_State',
    'South Dakota' : 'South_Dakota_Coyotes',
    'South Dakota St.' : 'South_Dakota_State_Jackrabbits',
    'South Florida' : 'South_Florida_Bulls',
    'Southern' : 'Southern_Jaguars',
    'Southern Ill.' : 'Southern_Illinois_Salukis',
    'Southern Miss' : 'Southern_Miss_Golden_Eagles',
    'Southern Utah' : 'Southern_Utah_Thunderbirds',
    'St. Francis (PA)' : 'Saint_Francis_University',
    'Stanford' : 'Stanford_Cardinal',
    'Stephen F. Austin' : 'Stephen_F._Austin_University',
    'Stillman': 'Stillman_College',
    'Stony Brook' : 'Stony_Brook_Seawolves',
    'Syracuse' : 'Syracuse_Orange',
    'TCU' : 'TCU_Horned_Frogs',
    'Temple' : 'Temple_Owls',
    'Tenn-Martin' : 'Tennessee-Martin',
    'Tennessee' : 'Tennessee_Volunteers',
    'Tennessee St.' : 'Tennessee_State_Tigers',
    'Tennessee Tech' : 'Tennessee_Technological_University',
    'Texas' : 'Texas_Longhorns',
    'Texas A&M' : 'Texas_A%26M_Aggies',
    'Texas Southern' : 'Texas_Southern_Tigers',
    'Texas St.' : 'Texas_State_Bobcats',
    'Texas Tech' : 'Texas_Tech_Red_Raiders',
    'Toledo' : 'Toledo_Rockets',
    'Towson' : 'Towson_Tigers',
    'Troy' : 'Troy_Trojans',
    'Tulane' : 'Tulane_Green_Wave',
    'Tulsa' : 'Tulsa_Golden_Hurricane',
    'Tuskegee': 'Tuskegee_University',
    'UAB' : 'UAB_Blazers',
    'UC Davis' : 'UC_Davis_Aggies',
    'UCF' : 'UCF_Knights',
    'UCLA' : 'UCLA_Bruins',
    'UNLV' : 'UNLV_Rebels',
    'USC' : 'USC_Trojans',
    'Utah' : 'Utah_Utes',
    'Utah St.' : 'Utah_State_Aggies',
    'UTEP' : 'UTEP_Miners',
    'UTSA' : 'UTSA_Roadrunners',
    'Valparaiso' : 'Valparaiso_Crusaders',
    'Vanderbilt' : 'Vanderbilt_Commodores',
    'Villanova' : 'Villanova_Wildcats',
    'Virginia' : 'Virginia_Cavaliers',
    'Virginia Military' : 'VMI_Keydets',
    'Virginia Tech' : 'Virginia_Tech_Hokies',
    'W. Michigan' : 'Western_Michigan_Broncos',
    'Wagner' : 'Wagner_College',
    'Wake Forest' : 'Wake_Forest_Demon_Deacons',
    'Washington' : 'Washington_Huskies',
    'Washington St.' : 'Washington_State_Cougars',
    'Weber St.' : 'Weber_State_University',
    'West Virginia' : 'West_Virginia_Mountaineers',
    'West. Kentucky' : 'Western_Kentucky_Hilltoppers',
    'Western Carolina' : 'Western_Carolina_Catamounts',
    'Western Ill.' : 'Western_Illinois_Leathernecks',
    'William & Mary' : 'William_%26_Mary_Tribe',
    'Wisconsin' : 'Wisconsin_Badgers',
    'Wofford' : 'Wofford_Terriers',
    'Wyoming' : 'Wyoming_Cowboys',
    'Yale' : 'Yale_Bulldogs',
    'Youngstown St.' : 'Youngstown_State_Penguins',
}

NBA_TEAMS = {
    'Boston': 'Boston_Celtics',
    'Brooklyn': 'Brooklyn_Nets',
    'New York': 'New_York_Knicks',
    'Philadelphia': 'Philadelphia_76ers',
    'Toronto': 'Toronto_Raptors',
    'Chicago': 'Chicago_Bulls',
}